# Generated by Django 5.1.1 on 2025-02-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierOpportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('mob_no', models.CharField(max_length=12)),
                ('email_add', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('upload_resume', models.FileField(upload_to='carrier_resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTieUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('agreement_date', models.DateField()),
                ('placement_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_desc', models.TextField()),
                ('course_duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_qualification', models.CharField(max_length=100)),
                ('instructor_Exp', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('no_of_student', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='instructor_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('social_media_link', models.URLField(max_length=3000)),
                ('our_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.instructor'),
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('packages', models.DecimalField(decimal_places=2, max_digits=10)),
                ('placement_date', models.DateTimeField()),
                ('company_tie_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.companytieups')),
            ],
        ),
    ]
