# Generated by Django 5.1.4 on 2025-02-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_footer_social_media_link_footer_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieropportunities',
            name='email_add',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='carrieropportunities',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrieropportunities',
            name='upload_resume',
            field=models.FileField(blank=True, null=True, upload_to='carrier_resumes/'),
        ),
        migrations.AlterField(
            model_name='companytieups',
            name='agreement_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companytieups',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companytieups',
            name='placement_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_desc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='facebook',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_Exp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='no_of_student',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placement',
            name='job_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
