# Generated by Django 5.1.4 on 2025-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_carrieropportunities_email_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
