# Generated by Django 5.1.4 on 2025-02-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_instructor_instructor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='our_courses',
        ),
    ]
