# Generated by Django 5.1.1 on 2025-03-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_alter_course_course_duration_technology_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='course',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='courses', to='academy.technology'),
        ),
        migrations.AddField(
            model_name='technology',
            name='tech_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
