# Generated by Django 5.1.1 on 2025-03-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_remove_technology_course_remove_technology_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
