# Generated by Django 5.1.1 on 2025-03-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_alter_enrollment_student_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='student_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_enrolled_in',
            field=models.ManyToManyField(blank=True, to='academy.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.userreg'),
        ),
    ]
