# Generated by Django 5.1.1 on 2025-03-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_student_image_alter_student_course_enrolled_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytieups',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
    ]
