# Generated by Django 5.1.1 on 2025-03-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_companytieups_company_image'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieropportunities',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='carrieropportunities',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('1-3 years', '1-3 years'), ('3+ years', '3+ years')], max_length=20),
        ),
    ]
