# Generated by Django 5.1.1 on 2025-04-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_alter_carrieropportunities_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieropportunities',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
