# Generated by Django 4.2.21 on 2025-07-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_alter_carrieropportunities_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='student',
        ),
        migrations.AddField(
            model_name='placement',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
