# Generated by Django 4.2.21 on 2025-07-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_remove_placement_student_placement_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='placement_photos/'),
        ),
    ]
