# Generated by Django 4.2.21 on 2025-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_placement_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
