# Generated by Django 4.2.21 on 2025-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='alt_text',
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active banners will be shown in the slideshow'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which images appear in the slideshow'),
        ),
    ]
