# Generated by Django 4.2.21 on 2025-08-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_remove_banner_alt_text_banner_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='course_banners/'),
        ),
    ]
