# Generated by Django 4.2.21 on 2025-08-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_course_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='packages',
        ),
    ]
